version: "3.3"
services:
  app:
    build:
      context: ./
      dockerfile: app.dockerfile
    working_dir: /var/www
    volumes:
    - ./:/var/www
    environment:
    - "DB_PORT=3306"
    - "DB_HOST=database"
  web:
    build:
      context: ./
      dockerfile: web.dockerfile
    working_dir: /var/www
    volumes:
    - ./:/var/www
    ports:
    - 8080:80
  database:
    image: mysql:latest
    volumes:
    - ./db_data:/var/lib/mysql
    environment:
    - "MYSQL_DATABASE=homestead"
    - "MYSQL_USER=homestead"
    - "MYSQL_PASSWORD=secret"
    - "MYSQL_ROOT_PASSWORD=secret"
    ports:
    - 1997:3306
